configatron.cache_expiry = 60 * 60 * 24 * 7
configatron.max_searches_per_user = 1000
configatron.max_posts_per_search = 1000
configatron.danbooru_server = ENV["LISTBOORU_DANBOORU_SERVER"] || "http://danbooru.donmai.us"
configatron.auth_key = ENV["LISTBOORU_AUTH_KEY"]
configatron.danbooru_user = ENV["LISTBOORU_DANBOORU_USER"]
configatron.danbooru_api_key = ENV["LISTBOORU_DANBOORU_API_KEY"]
configatron.amazon_key = ENV["AMAZON_KEY"]
configatron.amazon_secret = ENV["AMAZON_SECRET"]
configatron.sqs_url = ENV["LISTBOORU_SQS_URL"]
configatron.sqs_region = "us-west-2"